"""Type stub for the lightarray package.

Native functions come from ``lightarray._core``; the Python-level helpers
are declared below; every other public NumPy name exists at runtime (it is
copied from NumPy at import time), which ``__getattr__`` tells type checkers.
"""

from typing import Any

from numpy import bool_ as bool_
from numpy import dtype as dtype
from numpy import e as e
from numpy import euler_gamma as euler_gamma
from numpy import float32 as float32
from numpy import float64 as float64
from numpy import inf as inf
from numpy import int32 as int32
from numpy import int64 as int64
from numpy import nan as nan
from numpy import newaxis as newaxis
from numpy import pi as pi

from lightarray._core import *  # noqa: F401,F403
from lightarray._core import ndarray as ndarray

__version__: str

def mod(x1: Any, x2: Any) -> Any: ...
def zeros_like(a: Any, dtype: Any = None) -> Any: ...
def ones_like(a: Any, dtype: Any = None) -> Any: ...
def empty_like(a: Any, dtype: Any = None) -> Any: ...
def full_like(a: Any, fill_value: Any, dtype: Any = None) -> Any: ...
def asanyarray(a: Any, dtype: Any = None) -> Any: ...
def copy(a: Any) -> Any: ...
def shape(a: Any) -> tuple[int, ...]: ...
def size(a: Any) -> int: ...
def ndim(a: Any) -> int: ...
def atleast_1d(*arys: Any) -> Any: ...
def atleast_2d(*arys: Any) -> Any: ...
def hstack(tup: Any, **kwargs: Any) -> Any: ...
def vstack(tup: Any, **kwargs: Any) -> Any: ...
def row_stack(tup: Any, **kwargs: Any) -> Any: ...
def column_stack(tup: Any) -> Any: ...
def trapezoid(y: Any, x: Any = None, dx: float = 1.0, axis: int = -1) -> Any: ...
def squeeze(a: Any, axis: Any = None) -> Any: ...
def expand_dims(a: Any, axis: Any) -> Any: ...
def flip(m: Any, axis: Any = None) -> Any: ...
def diff(a: Any, n: int = 1, axis: int = -1, **kwargs: Any) -> Any: ...
def count_nonzero(a: Any, axis: Any = None, **kwargs: Any) -> Any: ...
def patch_module(module: Any, recursive: bool = True, verbose: bool = False, conversions: str = "lightarray") -> int: ...
def unpatch_module(module: Any, recursive: bool = True) -> int: ...
def is_patched(module: Any) -> bool: ...
def set_patched(module: Any, enabled: bool = True, recursive: bool = True, conversions: str = "lightarray") -> bool: ...

class patched:
    def __init__(self, module: Any, recursive: bool = True, conversions: str = "lightarray") -> None: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, *exc: Any) -> None: ...

def __array_namespace_info__() -> Any: ...

# Everything else in the numpy namespace (linalg, fft, random, polyfit, ...)
def __getattr__(name: str) -> Any: ...
