"""Type stubs for the native lightarray core."""

from collections.abc import Iterator, Sequence
from typing import Any, overload

import numpy as np
import numpy.typing as npt

MAX_NDIM: int

Shape = int | Sequence[int]
ArrayLike = "ndarray" | npt.ArrayLike
Scalar = float | int | np.floating | np.integer

class ndarray:
    """Mutable, C-contiguous float64 array with inline shape and strides."""

    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def strides(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[np.float64]: ...
    __array_priority__: float

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __array__(self, dtype: Any = None, copy: bool | None = None) -> np.ndarray: ...
    def __dlpack__(
        self,
        *,
        stream: Any = None,
        max_version: tuple[int, int] | None = None,
        dl_device: tuple[int, int] | None = None,
        copy: bool | None = None,
    ) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __copy__(self) -> ndarray: ...
    def __deepcopy__(self, memo: Any) -> ndarray: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any, modulo: Any = None) -> Any: ...
    def __rpow__(self, other: Any, modulo: Any = None) -> Any: ...
    def __matmul__(self, other: Any) -> Any: ...
    def __rmatmul__(self, other: Any) -> Any: ...
    def __neg__(self) -> ndarray: ...
    def __pos__(self) -> ndarray: ...
    def __abs__(self) -> ndarray: ...
    def __lt__(self, other: Any) -> npt.NDArray[np.bool_]: ...
    def __le__(self, other: Any) -> npt.NDArray[np.bool_]: ...
    def __gt__(self, other: Any) -> npt.NDArray[np.bool_]: ...
    def __ge__(self, other: Any) -> npt.NDArray[np.bool_]: ...
    def __eq__(self, other: Any) -> Any: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> Any: ...  # type: ignore[override]
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __iadd__(self, other: Any) -> ndarray: ...
    def __isub__(self, other: Any) -> ndarray: ...
    def __imul__(self, other: Any) -> ndarray: ...
    def __itruediv__(self, other: Any) -> ndarray: ...
    def __ifloordiv__(self, other: Any) -> ndarray: ...
    def __imod__(self, other: Any) -> ndarray: ...
    def __ipow__(self, other: Any, modulo: Any = None) -> ndarray: ...
    def fill(self, value: Any) -> None: ...

    # reductions: native with no arguments or a single integer axis, NumPy otherwise
    def sum(self, *args: Any, **kwargs: Any) -> Any: ...
    def prod(self, *args: Any, **kwargs: Any) -> Any: ...
    def mean(self, *args: Any, **kwargs: Any) -> Any: ...
    def max(self, *args: Any, **kwargs: Any) -> Any: ...
    def min(self, *args: Any, **kwargs: Any) -> Any: ...
    def var(self, *args: Any, **kwargs: Any) -> Any: ...
    def std(self, *args: Any, **kwargs: Any) -> Any: ...
    def argmax(self, *args: Any, **kwargs: Any) -> Any: ...
    def argmin(self, *args: Any, **kwargs: Any) -> Any: ...
    def any(self, *args: Any, **kwargs: Any) -> Any: ...
    def all(self, *args: Any, **kwargs: Any) -> Any: ...
    def cumsum(self, *args: Any, **kwargs: Any) -> Any: ...
    def cumprod(self, *args: Any, **kwargs: Any) -> Any: ...
    def dot(self, other: Any) -> Any: ...
    def clip(self, *args: Any, **kwargs: Any) -> Any: ...
    def round(self, *args: Any, **kwargs: Any) -> Any: ...
    @property
    def T(self) -> ndarray: ...
    def transpose(self, *args: Any, **kwargs: Any) -> Any: ...
    def reshape(self, *shape: Any) -> ndarray: ...
    def copy(self) -> ndarray: ...
    def flatten(self) -> ndarray: ...
    def ravel(self) -> ndarray: ...
    # Every other numpy.ndarray method and property is added at import time
    # by lightarray._fallback.install_ndarray_methods.
    def __getattr__(self, name: str) -> Any: ...

def array(object: Any, dtype: Any = None, /, **kwargs: Any) -> Any: ...
def asarray(object: Any, dtype: Any = None) -> Any: ...
def zeros(shape: Shape, dtype: Any = None) -> Any: ...
def ones(shape: Shape, dtype: Any = None) -> Any: ...
def empty(shape: Shape, dtype: Any = None) -> Any: ...
def full(shape: Shape, fill_value: float, dtype: Any = None) -> Any: ...
@overload
def arange(stop: float, /, *, dtype: Any = None) -> Any: ...
@overload
def arange(start: float, stop: float, step: float = 1.0, dtype: Any = None) -> Any: ...
def linspace(start: Any, stop: Any, num: int = 50, endpoint: bool = True, **kwargs: Any) -> Any: ...

# element-wise functions: lightarray in -> lightarray out, float in -> float out
def sin(x: Any) -> Any: ...
def cos(x: Any) -> Any: ...
def tan(x: Any) -> Any: ...
def arcsin(x: Any) -> Any: ...
def arccos(x: Any) -> Any: ...
def arctan(x: Any) -> Any: ...
def sinh(x: Any) -> Any: ...
def cosh(x: Any) -> Any: ...
def tanh(x: Any) -> Any: ...
def arcsinh(x: Any) -> Any: ...
def arccosh(x: Any) -> Any: ...
def arctanh(x: Any) -> Any: ...
def exp(x: Any) -> Any: ...
def exp2(x: Any) -> Any: ...
def expm1(x: Any) -> Any: ...
def log(x: Any) -> Any: ...
def log2(x: Any) -> Any: ...
def log10(x: Any) -> Any: ...
def log1p(x: Any) -> Any: ...
def sqrt(x: Any) -> Any: ...
def cbrt(x: Any) -> Any: ...
def square(x: Any) -> Any: ...
def reciprocal(x: Any) -> Any: ...
def absolute(x: Any) -> Any: ...
def fabs(x: Any) -> Any: ...
def abs(x: Any, *args: Any, **kwargs: Any) -> Any: ...
def negative(x: Any) -> Any: ...
def positive(x: Any) -> Any: ...
def sign(x: Any) -> Any: ...
def floor(x: Any) -> Any: ...
def ceil(x: Any) -> Any: ...
def trunc(x: Any) -> Any: ...
def rint(x: Any) -> Any: ...
def deg2rad(x: Any) -> Any: ...
def rad2deg(x: Any) -> Any: ...
def radians(x: Any) -> Any: ...
def degrees(x: Any) -> Any: ...
def isnan(x: Any) -> Any: ...
def isfinite(x: Any) -> Any: ...
def isinf(x: Any) -> Any: ...
def signbit(x: Any) -> Any: ...
def maximum(x1: Any, x2: Any) -> Any: ...
def minimum(x1: Any, x2: Any) -> Any: ...
def fmax(x1: Any, x2: Any) -> Any: ...
def fmin(x1: Any, x2: Any) -> Any: ...
def arctan2(x1: Any, x2: Any) -> Any: ...
def hypot(x1: Any, x2: Any) -> Any: ...
def copysign(x1: Any, x2: Any) -> Any: ...
def logaddexp(x1: Any, x2: Any) -> Any: ...
def concatenate(arrays: Sequence[Any], axis: int | None = 0, **kwargs: Any) -> Any: ...
def stack(arrays: Sequence[Any], axis: int | None = 0, **kwargs: Any) -> Any: ...
def where(condition: Any, x: Any = None, y: Any = None) -> Any: ...
def sort(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def transpose(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def add(x1: Any, x2: Any) -> Any: ...
def subtract(x1: Any, x2: Any) -> Any: ...
def multiply(x1: Any, x2: Any) -> Any: ...
def divide(x1: Any, x2: Any) -> Any: ...
def true_divide(x1: Any, x2: Any) -> Any: ...
def floor_divide(x1: Any, x2: Any) -> Any: ...
def remainder(x1: Any, x2: Any) -> Any: ...
def mod_(x1: Any, x2: Any) -> Any: ...
def power(x1: Any, x2: Any) -> Any: ...

# module-level forms of the methods above: la.sum(a, axis=0) == a.sum(axis=0)
def sum(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def prod(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def mean(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def max(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def min(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def var(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def std(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def argmax(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def argmin(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def any(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def all(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def cumsum(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def cumprod(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def dot(a: Any, b: Any) -> Any: ...
def clip(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def round(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def reshape(a: Any, *shape: Any) -> Any: ...
def copy(a: Any) -> Any: ...
def ravel(a: Any) -> Any: ...
def _noop() -> None: ...
